name: iOS Deploy to TestFlight

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
    
    - name: Install iOS dependencies
      run: |
        flutter pub get
        cd ios
        pod install
        cd ..
    
    - name: Setup code signing
      uses: apple-actions/import-codesigning-certs@v1
      with:
        p12-file-base64: ${{ secrets.P12_BASE64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
    
    - name: Setup provisioning profile
      uses: apple-actions/download-provisioning-profiles@v1
      with:
        bundle-id: 'com.example.waterUserNotify'
        profile-type: 'IOS_APP_STORE'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
    
    - name: Build iOS
      run: flutter build ios --release --no-codesign
    
    - name: Build IPA
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/Runner.xcarchive archive
        xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ios
        cd ..
    
    - name: Upload to TestFlight
      uses: apple-actions/upload-testflight@v1
      with:
        app-path: ios/build/ios/Runner.ipa
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }} 