name: iOS Simulator Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

jobs:
  test-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
    
    - name: Show Flutter version
      run: flutter --version
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Show iOS simulators
      run: xcrun simctl list devices
    
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install --repo-update
        cd ..
    
    - name: Run Flutter tests
      run: flutter test || echo "Tests failed, continuing with build"
    
    - name: Build iOS for simulator
      run: flutter build ios --simulator --debug
    
    - name: Boot iPhone 15 simulator
      run: |
        xcrun simctl boot "iPhone 15" || xcrun simctl boot "iPhone 14"
    
    - name: Launch app and take screenshot
      run: |
        # First, take a screenshot of the home screen
        xcrun simctl io booted screenshot home-screen.png
        echo "Home screen captured"
        
        # Install the app first
        echo "Installing app to simulator..."
        flutter install -d "iPhone 15"
        
        # Launch the app using simctl (more reliable)
        echo "Launching app via simctl..."
        xcrun simctl launch booted com.example.waterUserNotify || echo "Launch failed, trying alternative method"
        
        # Wait for app to fully load
        sleep 10
        
        # Take screenshot of the launched app
        xcrun simctl io booted screenshot app-launched.png
        echo "App launch screenshot captured"
        
        # Alternative method: Start flutter run and keep it running longer
        echo "Starting Flutter run for better app interaction..."
        flutter run -d "iPhone 15" --debug &
        FLUTTER_PID=$!
        
        # Wait longer for app to start properly
        sleep 45
        
        # Take screenshot of running app
        xcrun simctl io booted screenshot app-running.png
        echo "App running screenshot captured"
        
        # List all created files
        ls -la *.png
        
        # Kill flutter run
        kill $FLUTTER_PID 2>/dev/null || echo "Flutter process already ended"
    
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-simulator-screenshots
        path: |
          home-screen.png
          app-launched.png
          app-running.png
        retention-days: 30 