name: iOS Simulator Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

jobs:
  test-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
    
    - name: Show Flutter version
      run: flutter --version
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Show iOS simulators
      run: xcrun simctl list devices
    
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install --repo-update
        cd ..
    
    - name: Run Flutter tests
      run: flutter test
    
    - name: Build iOS for simulator
      run: flutter build ios --simulator --debug
    
    - name: Boot iPhone 15 simulator
      run: |
        xcrun simctl boot "iPhone 15" || xcrun simctl boot "iPhone 14"
    
    - name: Install app on simulator
      run: |
        flutter install -d "iPhone 15" || flutter install -d "iPhone 14"
    
    - name: Take screenshot
      run: |
        sleep 10
        xcrun simctl io booted screenshot screenshot.png || echo "Screenshot failed"
    
    - name: Upload screenshot
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-simulator-screenshot
        path: screenshot.png 