name: iOS Simulator Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

jobs:
  test-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install
        cd ..
    
    - name: Run iOS Simulator tests
      run: |
        flutter test
        flutter build ios --simulator
    
    - name: Run on iOS Simulator
      run: |
        # List available simulators
        xcrun simctl list devices
        
        # Boot iPhone 15 simulator
        xcrun simctl boot "iPhone 15"
        
        # Install and run the app
        flutter run -d "iPhone 15" --debug
        
    - name: Take screenshot
      run: |
        # Wait for app to load
        sleep 30
        
        # Take screenshot
        xcrun simctl io booted screenshot screenshot.png
        
    - name: Upload screenshot
      uses: actions/upload-artifact@v4
      with:
        name: ios-simulator-screenshot
        path: screenshot.png 